name: CoreGame
version: '1.0'
main: org.changchenguwu.coregame.main
api-version: '1.20'


#  §0：黑色
#  §1：深蓝色
#  §2：深绿色
#  §3：湖蓝色
#  §4：深红色
#  §5：紫色
#  §6：金色/橙色
#  §7：灰色
#  §8：深灰色
#  §9：蓝色
#  §a：绿色
#  §b：天蓝色
#  §c：红色
#  §d：粉红色
#  §e：黄色
#  §f：白色
#
#  §k：迷糊效果（随机字符）
#  §l：粗体
#  §m：删除线
#  §n：下划线
#  §o：斜体
#  §r：重置所有格式