name: CoreGame
version: '1.0'
main: org.changchenguwu.coregame.main
api-version: '1.20'
depend: [ProtocolLib]

#  §0：黑色
#  §1：深蓝色
#  §2：深绿色
#  §3：湖蓝色
#  §4：深红色
#  §5：紫色
#  §6：金色/橙色
#  §7：灰色
#  §8：深灰色
#  §9：蓝色
#  §a：绿色
#  §b：天蓝色
#  §c：红色
#  §d：粉红色
#  §e：黄色
#  §f：白色
#
#  §k：迷糊效果（随机字符）
#  §l：粗体
#  §m：删除线
#  §n：下划线
#  §o：斜体
#  §r：重置所有格式


commands:
  startupcore:
    description: 'Startup the core'
    usage: '/startupcore'
    permission: coregame.command.startupcore
    permission-message: 'You do not have permission to use this command.'
  changeteam:
    description: 'Change your team'
    usage: '/changeteam <team>'
    permission: coregame.command.changeteam
    permission-message: 'You do not have permission to use this command.'
  us:
    description: 'Update the screen'
    usage: '/coregame <subcommand>'
    permission: coregame.command.stools
    permission-message: 'You do not have permission to use this command.'
  loadallscreen:
    description: 'Load all screens from the display.yml file'
    usage: '/loadallscreen'
    permission: coregame.command.loadallscreen
    permission-message: 'You do not have permission to use this command.'
  stools:
    description: 'CoreGame plugin command'
    usage: '/coregame <subcommand>'
    permission: coregame.command.stools
    permission-message: 'You do not have permission to use this command.'
  coretemp:
    description: '调整核心温度'
    usage: '/coretemp <add|reduce> <数值>'
    permission: coregame.command.coretemp
    permission-message: '§c需要管理员权限'
  screenshake:
    description: '控制玩家屏幕抖动效果.'
    usage: '/<command> [start <强度> <持续时间(秒)>] or /<command> stop'
    permission: coregame.command.screenshake
    permission-message: '§c需要管理员权限'
  restorelightanimation:
    description: 'Restore the lighting animation'
    usage: '/restorelightanimation'
    permission: coregame.command.restorelightanimation
    permission-message: 'You do not have permission to use this command.'
  lightanimation:
    description: 'The lighting animation'
    usage: '/lightanimation'
    permission: coregame.command.lightanimation
    permission-message: 'You do not have permission to use this command.'
  debugsound:
    description: 'Plays a sound at a specified location for debugging'
    usage: '/debugsound <sound_name> <volume> <pitch> <world,x,y,z>'
    permission: coregame.command.debugsound
    permission-message: 'You do not have permission to use this command.'


permissions:
  coregame.command.startupcore:
    description: 'Allows the player to use the startupcore command.'
    default: op
  coregame.command.changeteam:
    description: 'Allows the player to use the changeteam command.'
    default: op
  coregame.command.us:
        description: 'Allows the player to use the us command.'
        default: op
  coregame.command.loadallscreen:
    description: '加载所有屏幕'
    default: op
  coregame.command.coretemp:
    description: '允许调整核心温度'
    default: op
  coregame.command.screenshake:
    description: '允许控制玩家屏幕抖动效果.'
    default: op
  coregame.command.stools:
    description: 'Allows the player to use the stools command.'
    default: op
  coregame.command.restorelightanimation:
    description: 'Allows the player to use the restorelightanimation command.'
    default: op
  coregame.command.lightanimation:
    description: 'The lighting animation'
    default: op
  coregame.command.debugsound:
    description: 'Allows the player to use the debugsound command.'
    default: op